FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
#COPY target/gs-mysql-data-0.1.0-docker-info.jar app.jar
#ECHO ${JAR_FILE}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]